# -*- coding: utf-8 -*-
"""生成本机 .env / settings.py（Key 来自 editor/settings.py），供 start_local.ps1 调用。"""
from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
EDITOR = HERE.parents[1] / "editor" / "settings.py"


def grab(text: str, name: str, default: str = "") -> str:
    m = re.search(rf'^{name}\s*=\s*"([^"]*)"', text, re.M)
    if m:
        return m.group(1)
    m = re.search(rf"^{name}\s*=\s*'([^']*)'", text, re.M)
    if m:
        return m.group(1)
    m = re.search(
        rf'^{name}\s*=\s*\(\s*"([^"]*)"\s*\)', text, re.M | re.S
    )
    if m:
        return m.group(1)
    return default


def main() -> int:
    if not EDITOR.is_file():
        print("missing", EDITOR, file=sys.stderr)
        return 1
    editor = EDITOR.read_text(encoding="utf-8")
    token = grab(editor, "AI_RELAY_TOKEN") or "gongwen-rly-7c4e9a2b1f08d635"
    deepseek = grab(editor, "DEEPSEEK_API_KEY")
    minimax = grab(editor, "MINIMAX_API_KEY")
    provider = "deepseek"
    port = "3000"
    if not deepseek and not minimax:
        print("DEEPSEEK_API_KEY / MINIMAX_API_KEY 都为空", file=sys.stderr)
        return 1

    env = (
        f"RELAY_PORT={port}\n"
        f"RELAY_TOKEN={token}\n"
        "CONTROL_ENABLED=1\n"
        "CONTROL_REQUIRE_USER=0\n"
        f"CONTROL_SECRET={token}\n"
        "CONTROL_REGISTER_MODE=open\n"
        f"AI_PROVIDER={provider}\n"
        f"DEEPSEEK_API_KEY={deepseek}\n"
        f"MINIMAX_API_KEY={minimax}\n"
    )
    (HERE / ".env").write_text(env, encoding="utf-8")

    settings = (
        "# auto-generated by bootstrap_local.py — do not commit\n"
        f"AI_PROVIDER = {provider!r}\n"
        "AI_USE_RELAY = False\n\n"
        f"MINIMAX_API_KEY = {minimax!r}\n"
        'MINIMAX_BASE_URL = "https://api.minimaxi.com/v1"\n'
        'MINIMAX_MODEL = "MiniMax-M3"\n'
        "MINIMAX_TIMEOUT = 90\n\n"
        f"DEEPSEEK_API_KEY = {deepseek!r}\n"
        'DEEPSEEK_BASE_URL = "https://api.deepseek.com"\n'
        'DEEPSEEK_MODEL = "deepseek-v4-flash"\n'
        "DEEPSEEK_TIMEOUT = 90\n"
    )
    (HERE / "settings.py").write_text(settings, encoding="utf-8")
    print("wrote .env and settings.py provider=", provider)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
